# Generated by Django 3.2.7 on 2022-02-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='isStudent',
            field=models.CharField(choices=[('student', 'Student'), ('nostudent', 'Not a Student')], max_length=20),
        ),
    ]
