# Generated by Django 3.2.7 on 2022-02-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20220211_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
