# Generated by Django 3.2.7 on 2022-03-19 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20220313_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 19, 3, 10, 98454)),
        ),
    ]
