# Generated by Django 3.2.7 on 2022-03-28 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_userscore_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Select Gender', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatbotuser',
            name='isStudent',
            field=models.CharField(choices=[('student', 'Student'), ('nostudent', 'Not a Student')], default='Select Student Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 19, 13, 5, 60591)),
        ),
    ]
