# Generated by Django 3.2.7 on 2022-03-28 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20220328_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='chatbotuser',
            name='isStudent',
        ),
        migrations.AlterField(
            model_name='userscore',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 19, 16, 30, 998689)),
        ),
    ]
